version: '3.8'

volumes:
  mysql_local_data:
  node_modules:

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    hostname: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bookshelf
    ports:
      - 3306:3306
    volumes:
      - mysql_local_data:/var/lib/mysql

  server:
    container_name: server
    build: ./server
    restart: unless-stopped
    tty: true
    networks:
      - bookshelf
    links:
      - db
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./server/:/app:delegated
    ports:
      - '8888:80'

  web:
    container_name: web
    build: ./web
    command: sh -c "npm run start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./web/:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - bookshelf
    links:
      - server

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - bookshelf
    links:
      - db

networks:
  bookshelf:
